apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    title: My Homelab
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - GitHub:
            - abbr: GH
              href: https://github.com/
        - GitLab:
            - abbr: GL
              href: https://gitlab.com/
        - ArgoCD:
            - abbr: AC
              href: http://192.168.1.227:32080/
    - Blog:
        - My Blog:
            - abbr: BLOG
              href: http://192.168.1.227:30080/
    - Social:
        - YouTube:
            - abbr: YT
              href: https://youtube.com/
        - LinkedIn:
            - abbr: LI
              href: https://linkedin.com/in/myprofile
        - Slack/Gmail:
            - abbr: SG
              href: https://mail.google.com/
  services.yaml: |
    - Cluster Apps:
        - ArgoCD:
            href: http://192.168.1.227:32080/
            description: GitOps deployment tool
        - Grafana:
            href: http://192.168.1.227:30090/
            description: Metrics & dashboards
    - My Services:
        - Homepage:
            href: http://192.168.1.227:32000/
            description: My Homelab homepage
        - Blog:
            href: http://192.168.1.227:30080/
            description: My personal blog
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
    - search:
        provider: duckduckgo
        target: _blank
    - links:
        show: true
        label: "Quick Access"
  docker.yaml: ""
